### ISSUE TITLE
Panic Handling Tables With Large Strings

### ISSUE THREAD

**Issue by tustvold** [influxdata/influxdb_iox#2089] opened 2021-07-22 10:58 UTC
We are seeing the following panics in tools

```
thread 'tokio-runtime-worker' panicked at 'failed to fit into offset type', /home/rust/project/arrow_util/src/string.rs:57:44
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at ./rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/panicking.rs:92:14
   2: core::option::expect_failed
             at ./rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/option.rs:1241:5
   3: core::option::Option<T>::expect
             at ./rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/option.rs:349:21
   4: arrow_util::string::PackedStringArray<K>::append
             at ./home/rust/project/arrow_util/src/string.rs:57:22
   5: mutable_buffer::column::Column::append
             at ./home/rust/project/mutable_buffer/src/column.rs:209:21
   6: mutable_buffer::chunk::MBChunk::write_columns
             at ./home/rust/project/mutable_buffer/src/chunk.rs:338:13
   7: mutable_buffer::chunk::MBChunk::write_table_batch
             at ./home/rust/project/mutable_buffer/src/chunk.rs:141:9
   8: server::db::Db::store_sequenced_entry
             at ./home/rust/project/server/src/db.rs:883:45
   9: server::db::Db::store_entry::{{closure}}
             at ./home/rust/project/server/src/db.rs:798:17
```

These relate to a table with large string values

```
select table_name,memory_bytes,row_count from chunks where storage = 'OpenMutableBuffer' order by memory_bytes/row_count desc limit 10;
+-----------------------------------+--------------+-----------+
| table_name                        | memory_bytes | row_count |
+-----------------------------------+--------------+-----------+
| query_log                         | 2149747767   | 26301     |
| query_log                         | 1286049746   | 21286     |
+-----------------------------------+--------------+-----------+
```

Currently it is assumed that a chunk can fit inside a single RecordBatch - this error would imply that a column has more string data than can fit in a single StringArray. This consists of a single contiguous run of characters, with a separate array of i32 to store indexes into that array. This implies a limit of 2147483647 bytes of string data per column. 

Some ideas on how to address this:

* Introduce some form of size-awareness to the lifecycle
* Introduce batching to the MUB, RUB to yield multiple RecordBatch if necessary
* Limit the maximum string payload to be 2147483647 / CHUNK_MAX_ROWS

**Comment by e-dard** [comment] 2021-07-22 14:32
I think that the most general thing we can do to directly address this is add a size-awareness to the lifecycle, even if it's not configurable by operators.

Batching doesn't really solve the problem if you could just technically write in more than 2GB into a row. The third option of limiting makes sense but since the limit is dynamic (or at least dependent on other configuration values) I would argue it could be confusing.

Having said all we still need to have a per-value limit plus batching eventually because we can't guarantee that even if we control the batch sizes we push down into IOx we can't easily control what comes out (based on query parameters).

**Comment by e-dard** [comment] 2021-07-22 14:33
Maybe the very first thing should just be to drop large line-protocol points? If we limit them to say 1KB then we will go a long way to avoiding this problem happening often. The rows I was seeing for `query_log` had 10MB rows in them...

**Comment by alamb** [comment] 2021-07-23 19:25
Here is a reproducer

```diff
diff --git a/mutable_buffer/src/chunk.rs b/mutable_buffer/src/chunk.rs
index c0caa301..46ddedfa 100644
--- a/mutable_buffer/src/chunk.rs
+++ b/mutable_buffer/src/chunk.rs
@@ -851,4 +851,42 @@ mod tests {
             response
         );
     }
+
+
+    #[test]
+    fn error_on_string_exhaustion() {
+        // ensure the MUB errors reasonably when string buffer is exceeded
+
+        let lp = vec![
+            "h2o,state=MA temp=70.4 100",
+        ]
+        .join("\n");
+        let mut chunk = write_lp_to_new_chunk(&lp).unwrap();
+
+        // 1MB strings
+        let s = "0123456789";
+        let repeated = std::iter::repeat(s)
+            .take((1024*1024) / s.len())
+            //.take(1)
+            .collect::<String>();
+
+        let num_strings = 10000;
+        let lp = format!("h2o,state=MA temp=666,string=\"{}\" 1000", repeated);
+
+        // stuff the mub!
+        println!("Starting....");
+        for i in 0..num_strings {
+            if (i % 100) == 0 {
+                println!("({})", i);
+            } else if  (i % 10) == 0 {
+                print!("({})", i);
+            }
+            write_lp_to_chunk(&lp, &mut chunk).expect("writing to the mub");
+        }
+
+        // make sure we write all the data in there
+        assert_eq!(chunk.rows(), 1+num_strings);
+    }
+
+
 }
```

Note you basically have to run this in release mode otherwise it takes minutes

```
(arrow_dev) alamb@MacBook-Pro:~/Software/influxdb_iox$ cargo test --release -p mutable_buffer -- exhaustion --nocapture
   Compiling mutable_buffer v0.1.0 (/Users/alamb/Software/influxdb_iox/mutable_buffer)
    Finished release [optimized + debuginfo] target(s) in 3.58s
     Running unittests (target/release/deps/mutable_buffer-8b941cade47cda01)

running 1 test
Starting....
(0)
(10)(20)(30)(40)(50)(60)(70)(80)(90)(100)
(110)(120)(130)(140)(150)(160)(170)(180)(190)(200)
(210)(220)(230)(240)(250)(260)(270)(280)(290)(300)
(310)(320)(330)(340)(350)(360)(370)(380)(390)(400)
(410)(420)(430)(440)(450)(460)(470)(480)(490)(500)
(510)(520)(530)(540)(550)(560)(570)(580)(590)(600)
(610)(620)(630)(640)(650)(660)(670)(680)(690)(700)
(710)(720)(730)(740)(750)(760)(770)(780)(790)(800)
(810)(820)(830)(840)(850)(860)(870)(880)(890)(900)
(910)(920)(930)(940)(950)(960)(970)(980)(990)(1000)
(1010)(1020)(1030)(1040)(1050)(1060)(1070)(1080)(1090)(1100)
(1110)(1120)(1130)(1140)(1150)(1160)(1170)(1180)(1190)(1200)
(1210)(1220)(1230)(1240)(1250)(1260)(1270)(1280)(1290)(1300)
(1310)(1320)(1330)(1340)(1350)(1360)(1370)(1380)(1390)(1400)
(1410)(1420)(1430)(1440)(1450)(1460)(1470)(1480)(1490)(1500)
(1510)(1520)(1530)(1540)(1550)(1560)(1570)(1580)(1590)(1600)
(1610)(1620)(1630)(1640)(1650)(1660)(1670)(1680)(1690)(1700)
(1710)(1720)(1730)(1740)(1750)(1760)(1770)(1780)(1790)(1800)
(1810)(1820)(1830)(1840)(1850)(1860)(1870)(1880)(1890)(1900)
(1910)(1920)(1930)(1940)(1950)(1960)(1970)(1980)(1990)(2000)
thread 'chunk::tests::error_on_string_exhaustion' panicked at 'failed to fit into offset type', /Users/alamb/Software/influxdb_iox/arrow_util/src/string.rs:57:44
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
(2010)(2020)(2030)(2040)test chunk::tests::error_on_string_exhaustion ... FAILED

failures:

failures:
    chunk::tests::error_on_string_exhaustion

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 8 filtered out; finished in 8.77s
```

**Comment by alamb** [comment] 2021-07-23 19:26
Stack trace is 
```shell
thread 'chunk::tests::error_on_string_exhaustion' panicked at 'failed to fit into offset type', /Users/alamb/Software/influxdb_iox/arrow_util/src/string.rs:57:44
stack backtrace:
   0: rust_begin_unwind
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/panicking.rs:92:14
   2: core::option::expect_failed
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/option.rs:1241:5
   3: core::option::Option<T>::expect
             at /Users/alamb/.rustup/toolchains/1.53.0-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/option.rs:349:21
   4: arrow_util::string::PackedStringArray<K>::append
             at /Users/alamb/Software/influxdb_iox/arrow_util/src/string.rs:57:22
   5: mutable_buffer::column::Column::append
             at ./src/column.rs:209:21
   6: mutable_buffer::chunk::MBChunk::write_columns
             at ./src/chunk.rs:340:13
   7: mutable_buffer::chunk::MBChunk::write_table_batch
             at ./src/chunk.rs:141:9
   8: mutable_buffer::chunk::test_helpers::write_lp_to_chunk
             at ./src/chunk.rs:381:17
   9: mutable_buffer::chunk::tests::error_on_string_exhaustion
             at ./src/chunk.rs:884:13
  10: core::ops::function::FnOnce::call_once
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
(2010)(2020)(2030)(2040)test chunk::tests::error_on_string_exhaustion ... FAILED

failures:

failures:
    chunk::tests::error_on_string_exhaustion

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 8 filtered out; finished in 8.83s
```

**Comment by alamb** [comment] 2023-08-11 17:28
This code is no longer in the repository so closing it

**Closed by alamb** 2023-08-11 17:28 UTC
Labels: kind/bug, panic, team/iox/query
