### ISSUE TITLE
Panic Persisting Empty List of Chunks

### ISSUE THREAD

**Issue by tustvold** [influxdata/influxdb_iox#1966] opened 2021-07-12 17:32 UTC
We're seeing a number of panics trying to split and persist an empty list of chunks.

It is unclear to me why this is occurring, but it may be related to #1957 

```
level=info msg="persisting chunks" table=istio_response_bytes partition="2021-07-12 17:00:00" span=1649267441665 target="server::db::lifecycle" location="server/src/db/lifecycle.rs:219" time=1626110471322217630
level=info msg="splitting and persisting chunks" table_name=istio_response_bytes partition_key="2021-07-12 17:00:00" chunk_ids=[] span=1649267441665 target="server::db::lifecycle::persist" location="server/src/db/lifecycle/persist.rs:43" time=1626110471322232837
thread 'tokio-runtime-worker' panicked at 'No chunks provided to compact plan', /home/rust/project/query/src/frontend/reorg.rs:202:21
stack backtrace:
level=error msg="thread 'tokio-runtime-worker' panicked at 'No chunks provided to compact plan', /home/rust/project/query/src/frontend/reorg.rs:202:21" target="panic_logging" location="panic_logging/src/lib.rs:110" time=1626110471322302325
   0: std::panicking::begin_panic
             at ./rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:519:12
   1: query::frontend::reorg::ReorgPlanner::scan_and_sort_plan
             at ./home/rust/project/query/src/frontend/reorg.rs:202:21
   2: query::frontend::reorg::ReorgPlanner::split_plan
             at ./home/rust/project/query/src/frontend/reorg.rs:160:13
   3: server::db::lifecycle::persist::persist_chunks::{{closure}}
             at ./home/rust/project/server/src/db/lifecycle/persist.rs:82:30
   4: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/future/mod.rs:80:19
   5: <tracker::task::future::TrackedFuture<F> as core::future::future::Future>::poll
             at ./home/rust/project/tracker/src/task/future.rs:66:20
   6: <server::db::lifecycle::LockableCatalogPartition as lifecycle::LockablePartition>::persist_chunks::{{closure}}
             at ./home/rust/project/server/src/db/lifecycle.rs:222:43
   7: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/future/mod.rs:80:19
   8: tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.1/src/runtime/task/core.rs:243:17
   9: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.1/src/loom/std/unsafe_cell.rs:14:9
  10: tokio::runtime::task::core::CoreStage<T>::poll
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.1/src/runtime/task/core.rs:233:13
  11: tokio::runtime::task::harness::poll_future::{{closure}}
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.1/src/runtime/task/harness.rs:438:23
  12: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at ./rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panic.rs:344:9
  13: std::panicking::try::do_call
             at ./rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:379:40
  14: std::panicking::try
             at ./rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:343:19
  15: std::panic::catch_unwind
             at ./rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panic.rs:431:14
  16: tokio::runtime::task::harness::poll_future
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.1/src/runtime/task/harness.rs:425:19
  17: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.1/src/runtime/task/harness.rs:89:9
  18: tokio::runtime::task::harness::Harness<T,S>::poll
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.1/src/runtime/task/harness.rs:59:15
  19: tokio::runtime::task::raw::RawTask::poll
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.1/src/runtime/task/raw.rs:70:18
  20: tokio::runtime::task::Notified<S>::run
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.1/src/runtime/task/mod.rs:171:9
  21: tokio::runtime::thread_pool::worker::Context::run_task::{{closure}}
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.1/src/runtime/thread_pool/worker.rs:349:13
  22: tokio::coop::with_budget::{{closure}}
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.1/src/coop.rs:106:9
  23: std::thread::local::LocalKey<T>::try_with
             at ./rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/thread/local.rs:376:16
  24: std::thread::local::LocalKey<T>::with
             at ./rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/thread/local.rs:352:9
  25: tokio::coop::with_budget
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.1/src/coop.rs:99:5
  26: tokio::coop::budget
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.1/src/coop.rs:76:5
  27: tokio::runtime::thread_pool::worker::Context::run_task
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.1/src/runtime/thread_pool/worker.rs:348:9
  28: tokio::runtime::thread_pool::worker::Context::run
  29: tokio::runtime::thread_pool::worker::run::{{closure}}
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.1/src/runtime/thread_pool/worker.rs:303:17
  30: tokio::macros::scoped_tls::ScopedKey<T>::set
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.1/src/macros/scoped_tls.rs:61:9
  31: tokio::runtime::thread_pool::worker::run
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.1/src/runtime/thread_pool/worker.rs:300:5
  32: tokio::runtime::thread_pool::worker::Launch::launch::{{closure}}
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.1/src/runtime/thread_pool/worker.rs:279:45
  33: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.1/src/runtime/blocking/task.rs:42:21
  34: tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.1/src/runtime/task/core.rs:243:17
  35: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.1/src/loom/std/unsafe_cell.rs:14:9
  36: tokio::runtime::task::core::CoreStage<T>::poll
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.1/src/runtime/task/core.rs:233:13
  37: tokio::runtime::task::harness::poll_future::{{closure}}
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.1/src/runtime/task/harness.rs:438:23
  38: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at ./rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panic.rs:344:9
```

**Comment by alamb** [comment] 2021-07-12 17:49
dupe of https://github.com/influxdata/influxdb_iox/issues/1958 as well

**Closed** 2021-07-12 18:28 UTC
Labels: bug
