### ISSUE TITLE
Excessive compactor catalog queries

### ISSUE THREAD

**Issue by domodwyer** [influxdata/influxdb_iox#7973] opened 2023-06-12 12:23 UTC
A compactor problem currently exists where an over provisioned and extremely idle compactor winds up in a hot loop, endlessly busy-polling until work becomes available.  This has only been observed on clusters that have minimal workload, and the issue causes excessive load on the catalog.

**An example of an idle compactor that should not receive extra resources looks like this:**
![image](https://github.com/influxdata/influxdb_iox/assets/73478756/d4f4ac32-0457-470c-ab57-69c9af05f663)
Note the concurrency never flat-lines at an upper limit, and regularly drops to 0.
Additionally the backlog of jobs ready to run ("pending") spends a lot of time at 0.
Even though this compactor is doing work, it is relatively idle.  The key point here is that it is struggling to find enough work to do (indicated by a lack of pending jobs), and is likely causing some extra load on the catalog. Extra CPU will provide no benefit to this compactor and primarily result in extra load on the catalog.  In this specific cluster the excess load is not currently a problem for the catalog, but big increases to compactor CPU from here would become a problem.  Cutting CPU by 50% is likely fine.

**An example of a non-idle compactor that can safely be given significantly more resources looks like this:**
![image](https://github.com/influxdata/influxdb_iox/assets/73478756/56587dc2-51f8-4ace-b6f4-ced15e14dd28)
Note the job concurrency clearly indicates its configured limit (8), which it is frequently flat-lined at.
Additionally, the backlog of jobs ready to run ("pending") rarely touches 0.
These indicate this compactor has plenty of work to do, and is having no difficulty finding that work.  Whether or not this compactor would benefit from extra CPU is a separate question, but it is safe to add CPU.  If adding significant CPU (e.g. double it), it would be prudent to recheck for idleness, but CPU increases in the of 2x-4x are unlikely to cause catalog problems for this cluster.

**What if your'e observing high catalog query rates**
![image](https://github.com/influxdata/influxdb_iox/assets/73478756/2c05f994-35b7-43bb-978b-02bf585fdff8)
Note the significantly longer time spent at 0 pending jobs.  This compactor is very significantly over provisioned.
This CPU can be cut by 50% repeatedly until the time spent at 0 pending jobs comes down.

**In general**, if the compactor shows a clear need for additional CPU, it is safe to add CPU without hesitation (avoiding the addition of needed CPU is more of a concern).  The issue is that when the compactor is extremely over provisioned (as indicated by it having trouble finding enough work), it can cause excess load on the catalog.

**When the compactor is causing excess queries, it looks like this:**
![image](https://github.com/influxdata/influxdb_iox/assets/9275968/9fe46f9e-bc18-4c64-97ae-f38cf770ac89)
In the above, the compactor is responsible for an order of magnitude more queries than any other component on average, despite doing nothing productive, and peaks at an excessive ~2,500 queries per second.

Delays could fix this but would likely cause other issues.  A more controlled query rate throttling is safer, and may offer a maintenance free option.  That is being pursued.

This ticket is to implement a proper/robust solution, and serves as a warning for code references.

**Comment by Joe-Blount** [comment] 2023-06-12 14:58
What we know at this point, is that if a compactor has significantly more than 10x the amount of CPU it needs to do its work, it will query the catalog at a high rate that causes an issue.  `eu-central-1` (where this problem was noticed) has had its CPU reduced by 90% and it's compactor is still very idle, although the query rate has come down significantly.  Since it is still very idle, we know it still has much more CPU than it needs.  I think its still has double the necessary resources (a guess) suggesting this problem was observed with 20x or more the necessary CPU.  Note that having 20x the necessary CPU is a potential issue for tiny clusters only.

The short term option for fixing this would be adding delay, there is not an obvious place to add a delay that is is both effective and universally safe. 
- adding a delay between when the compactor queries for partitions with activity in the last 10m would be ineffective.  The list of partitions with activity can be quite large, taking minutes to evaluate (it is the queries to evaluate each partition that are thought to cause the issue of this ticket).  assume it takes 5m to do all the queries evaluating partitions with activity in the last 10m.  Slamming the catalog for 5m then taking a break (even for minutes) doesn't solve the problem because slowing the catalog for 5m isn't ok, even the delay gives it a break before the next 5m of overload.
- Adding a delay between evaluation of each partition would address this problem (so the compactor would query for partitions with activity in the last 30m, then use delays to throttle how quickly it evaluates them).  However, the "hot partition starvation" issue would be significantly worsened by such a delay.  So delaying between evaluations is useful, but it can only be enabled on the tiny/over-resourced clusters.  

The real fix for this comes when we get rid of the query of all partitions having activity in the last 10m, because then the compactor quits creating large lists of partitions that it must recheck to see if they need compacted.  Such changes are already planned after the scheduler is separated from the compactor.

So to summarize the near term options:
1) if we make no code change on behalf of this issue, new/tiny clusters need to have an appropriately small compactor resources, which are grown as necessary as the cluster grows.  
2) if we add delays, new tiny/tiny clusters need the delay set, and as they grow they need the delay removed and compactor resources still need grown as the cluster grows.  

The consequences of the above options are:
1) (current code / no added delays) compactor resources need set appropriately for the cluster and grown as necessary as the cluster grows.  Undersizing or oversizing the compactor resources will cause issues.
2) (if we add delays) the delay needs set for tiny clusters and removed as the cluster grows.  Commpactor resources need grown as the cluster grows. Undersizing compactor resources will cause issues.

My current belief is that adding delays to address this problem will add to the maintenance of new clusters with no clear value add over just sizing the CPU appropriately to begin with.

**Comment by domodwyer** [comment] 2023-06-12 16:15
I've confirmed that we can't easily scale the CPU limits for dedicated clusters - the compactor just uses as much CPU as the dedicated box has available. We also can't easily change the box size for the compactor specifically.

This sounds like the perfect storm combination! Perhaps it is time to investigate adding a delay.

**Comment by Joe-Blount** [comment] 2023-06-13 19:36
Since this issue linked to from config settings, and may be consulted by people trying to manage the current situation, I significantly edited the problem description above to be more focused on guidance.

**Comment by crepererum** [comment] 2023-07-06 09:05
BTW: While reviewing the partition catalog queries, I've also found that some of them don't use an index, e.g.:

https://github.com/influxdata/influxdb_iox/blob/a25fd6015d2972b2997eec8a956047921255ae1b/iox_catalog/src/postgres.rs#L1315-L1338

Now if you throttle the compaction scheduler queries enough, this may not be an issue but if you run this request often, I think we should add an index on `new_file_at` (which makes `parquet_file` creation slightly more expensive, but at least you don't need to scan the entire `partitions` table anymore).

**Comment by Joe-Blount** [comment] 2023-07-07 16:00
@crepererum I'll add a separate issue for adding the index.

Here's a summary of the causes & fixes for the excessive query rate:

1) the hard coded 10m lookback for work to do resulted in excessive evaluations of partitions that don't need compacted.  For example, assume a cluster is idle enough that within 1 minute it can evaluate all partitions with activity within the last 10m.  In the next batch of partitions to evaluate, those with activity in 9 of the 10 minutes are guaranteed to not need compacted (or they would have been compacted in the prior batch).  Rechecking them requires the compactor query the catalog. This is cheap & easy for the compactor, potentially some work for the catalog.  So a 10m lookback on semi-idle cluster creates a lot of worthless queries to the catalog.  https://github.com/influxdata/influxdb_iox/pull/8124 corrected this.

2) A couple idle clusters were configured for far more concurrency in the compactor than they needed (6 or 12).  So the compactor would concurrently generate the worthless queries to the catalog. This makes the 10m lookback problem worse because getting through the busywork faster just means more busywork in the next batch.  And the extra concurrency means it can rapidly get through that busywork (which is how it slams the catalog).  Concurrency in these semi-idle clusters was reduced to 1.

The above two changes greatly reduced the spikes in query rate from the compactor.  What remained was occasional (smaller) spikes, typically at the end of a batch of partitions being evaluated.  I suspect the sorting of the batch of partitions made it less likely for the last partitions to need compacted.  For most of the processing, the partitions needing compacted would "soak up" the concurrency limit, so there wasn't much left to hit the catalog.  Within a batch of partitions, any long sequence of partition IDs not needing compacted could cause the compactor the hit the catalog harder.

So the final change (https://github.com/influxdata/influxdb_iox/pull/8173) was throttling the rate of partition evaluation in the compactor.  Every time a batch of partitionIDs is retrieved, the throttling rate is set such that it will take at least 5m to evaluate them.  The semi-idle clusters that previously raced through batches in a minute or two are now slowed, and the busy clusters minimally affected.

These graphs show the final change removing what was left of the query rate spikes in the two worst behaving clusters.
![image](https://github.com/influxdata/influxdb_iox/assets/73478756/f8c02b7b-8a19-4f33-b173-32e456e48391)
![image](https://github.com/influxdata/influxdb_iox/assets/73478756/8396861c-554c-45a5-87af-5f9515d90e4b)

**Closed by Joe-Blount** 2023-07-07 16:00 UTC
Labels: kind/bug, domain/iox/compactor, team/iox/write-path
