### ISSUE TITLE
Ingester: update ingester startup to seek to minimum sequence numbers

### ISSUE THREAD

**Issue by pauldix** [influxdata/influxdb_iox#3704] opened 2022-02-09 20:28 UTC
Once the ingester persistence is saving its `min_unpersisted_sequence_number`, update the write buffer initialization in the Ingester to seek to those sequence numbers.

When initializing, do not buffer up data that has already been persisted.

**Comment by domodwyer** [comment] 2022-03-09 11:57
I think this is a dupe of #3851 and this task is now complete (#3940) right?

**Closed** 2022-03-09 16:10 UTC
