### ISSUE TITLE
flaky test: end_to_end_ng_cases::querier::multi_ingester::basic_multi_ingesters

### ISSUE THREAD

**Issue by domodwyer** [influxdata/influxdb_iox#4426] opened 2022-04-26 10:43 UTC
https://app.circleci.com/pipelines/github/influxdata/influxdb_iox/18500/workflows/8ed3bf8a-5ded-4669-8650-b22577bd5f66/jobs/154402

**Comment by alamb** [comment] 2022-04-26 16:45
Seems like a dupe of https://github.com/influxdata/influxdb_iox/issues/4395

**Comment by alamb** [comment] 2022-04-27 15:06
Closing as a dupe

**Closed by alamb** 2022-04-27 15:06 UTC
