### ISSUE TITLE
Support streaming Partition snapshots to Parquet to object storage

### ISSUE THREAD

**Issue by pauldix** [influxdata/influxdb_iox#530] opened 2020-12-05 14:14 UTC
This would build on top of #526. Currently, it converts an in-memory partition to a RecordBatch, writes that into an in-memory buffer and then writes that to object storage. Instead, the RecordBatch should be streamed to the Parquet format while streaming to object storage.

**Comment by jacobmarble** [comment] 2021-11-11 02:28
(This issue is almost a year old, so my comment may not be worth anything now.)

This is very difficult to accomplish. Object store APIs require the size and checksum before the payload uploaded. In the cloud storage services, I ended up writing potentially large objects to disk before upload. A good compromise might be to allow an on-disk buffer, which isn't expensive with ephemeral local block devices.

**Comment by jacobmarble** [comment] 2021-11-11 02:29
@pauldix can this be closed?

**Comment by jacobmarble** [comment] 2021-11-11 03:16
Duplicate of #818

**Closed by jacobmarble** 2021-11-11 03:16 UTC
Labels: invalid, performance, crate/object_store
