### ISSUE TITLE
DataFusion ExternalSort Memory Accounting Underflow Panic

### ISSUE THREAD

**Issue by tustvold** [influxdata/influxdb_iox#3820] opened 2022-02-22 17:18 UTC
This is likely an upstream bug, but creating here until I've had a chance to properly triage it. We are seeing panics due to the new memory manager, in particular the external sort functionality.

```
2022-02-22T17:09:19.117634379Z level=error msg="Thread panic" panic_info="panicked at 'Tracker total memory shrink by 6088256 underflow, current value is : 0', /usr/local/cargo/git/checkouts/arrow-datafusion-71ae82d9dec9a01c/81e76ed/datafusion/src/execution/memory_manager.rs:299:16" target="panic_logging" location="panic_logging/src/lib.rs:94" time=1645549759117538691
2022-02-22T17:09:19.117663268Z thread 'IOx Query Executor Thread' panicked at 'Tracker total memory shrink by 6088256 underflow, current value is : 0', /usr/local/cargo/git/checkouts/arrow-datafusion-71ae82d9dec9a01c/81e76ed/datafusion/src/execution/memory_manager.rs:299:16
2022-02-22T17:09:19.117695985Z stack backtrace:
2022-02-22T17:09:19.117699132Z    0: rust_begin_unwind
2022-02-22T17:09:19.117702665Z              at ./rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:498:5
2022-02-22T17:09:19.117706029Z    1: core::panicking::panic_fmt
2022-02-22T17:09:19.117710623Z              at ./rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/panicking.rs:107:14
2022-02-22T17:09:19.117714121Z    2: core::result::unwrap_failed
2022-02-22T17:09:19.117717204Z              at ./rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/result.rs:1613:5
2022-02-22T17:09:19.117721095Z    3: core::result::Result<T,E>::expect
2022-02-22T17:09:19.117724325Z              at ./rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/result.rs:1255:23
2022-02-22T17:09:19.117741128Z    4: datafusion::execution::memory_manager::MemoryManager::shrink_tracker_usage
2022-02-22T17:09:19.117768826Z              at ./usr/local/cargo/git/checkouts/arrow-datafusion-71ae82d9dec9a01c/81e76ed/datafusion/src/execution/memory_manager.rs:299:9
2022-02-22T17:09:19.117796637Z    5: datafusion::execution::memory_manager::MemoryManager::drop_consumer
2022-02-22T17:09:19.117803548Z              at ./usr/local/cargo/git/checkouts/arrow-datafusion-71ae82d9dec9a01c/81e76ed/datafusion/src/execution/memory_manager.rs:374:9
2022-02-22T17:09:19.117811104Z    6: datafusion::execution::runtime_env::RuntimeEnv::drop_consumer
2022-02-22T17:09:19.117816109Z              at ./usr/local/cargo/git/checkouts/arrow-datafusion-71ae82d9dec9a01c/81e76ed/datafusion/src/execution/runtime_env.rs:78:9
2022-02-22T17:09:19.117822270Z    7: <datafusion::physical_plan::sorts::sort::ExternalSorter as core::ops::drop::Drop>::drop
2022-02-22T17:09:19.117848015Z              at ./usr/local/cargo/git/checkouts/arrow-datafusion-71ae82d9dec9a01c/81e76ed/datafusion/src/physical_plan/sorts/sort.rs:200:9
2022-02-22T17:09:19.117870575Z    8: core::ptr::drop_in_place<datafusion::physical_plan::sorts::sort::ExternalSorter>
2022-02-22T17:09:19.117876927Z              at ./rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/ptr/mod.rs:188:1
2022-02-22T17:09:19.117893161Z    9: core::ptr::drop_in_place<datafusion::physical_plan::sorts::sort::do_sort::{{closure}}>
2022-02-22T17:09:19.117912652Z              at ./usr/local/cargo/git/checkouts/arrow-datafusion-71ae82d9dec9a01c/81e76ed/datafusion/src/physical_plan/sorts/sort.rs:587:1
2022-02-22T17:09:19.117937218Z   10: core::ptr::drop_in_place<core::future::from_generator::GenFuture<datafusion::physical_plan::sorts::sort::do_sort::{{closure}}>>
2022-02-22T17:09:19.117957084Z              at ./rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/ptr/mod.rs:188:1
2022-02-22T17:09:19.117988560Z   11: core::ptr::drop_in_place<<datafusion::physical_plan::sorts::sort::SortExec as datafusion::physical_plan::ExecutionPlan>::execute::{{closure}}>
2022-02-22T17:09:19.118005373Z              at ./usr/local/cargo/git/checkouts/arrow-datafusion-71ae82d9dec9a01c/81e76ed/datafusion/src/physical_plan/sorts/sort.rs:499:9
2022-02-22T17:09:19.118043938Z   12: core::ptr::drop_in_place<core::future::from_generator::GenFuture<<datafusion::physical_plan::sorts::sort::SortExec as datafusion::physical_plan::ExecutionPlan>::execute::{{closure}}>>
2022-02-22T17:09:19.118053604Z              at ./rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/ptr/mod.rs:188:1
2022-02-22T17:09:19.118170817Z   13: core::ptr::drop_in_place<alloc::boxed::Box<dyn core::future::future::Future+Output = core::result::Result<core::pin::Pin<alloc::boxed::Box<dyn datafusion::physical_plan::RecordBatchStream+Item = core::result::Result<arrow::record_batch::RecordBatch,arrow::error::ArrowError>+core::marker::Send+core::marker::Sync>>,datafusion_common::error::DataFusionError>+core::marker::Send>>
2022-02-22T17:09:19.118181236Z              at ./rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/ptr/mod.rs:188:1
2022-02-22T17:09:19.118303658Z   14: core::ptr::drop_in_place<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future+Output = core::result::Result<core::pin::Pin<alloc::boxed::Box<dyn datafusion::physical_plan::RecordBatchStream+Item = core::result::Result<arrow::record_batch::RecordBatch,arrow::error::ArrowError>+core::marker::Send+core::marker::Sync>>,datafusion_common::error::DataFusionError>+core::marker::Send>>>
2022-02-22T17:09:19.118314379Z              at ./rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/ptr/mod.rs:188:1
2022-02-22T17:09:19.118331042Z   15: core::ptr::drop_in_place<<datafusion::physical_plan::projection::ProjectionExec as datafusion::physical_plan::ExecutionPlan>::execute::{{closure}}>
2022-02-22T17:09:19.118341195Z              at ./usr/local/cargo/git/checkouts/arrow-datafusion-71ae82d9dec9a01c/81e76ed/datafusion/src/physical_plan/projection.rs:161:20
2022-02-22T17:09:19.118410683Z   16: core::ptr::drop_in_place<core::future::from_generator::GenFuture<<datafusion::physical_plan::projection::ProjectionExec as datafusion::physical_plan::ExecutionPlan>::execute::{{closure}}>>
2022-02-22T17:09:19.118419724Z              at ./rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/ptr/mod.rs:188:1
2022-02-22T17:09:19.118501755Z   17: core::ptr::drop_in_place<alloc::boxed::Box<dyn core::future::future::Future+Output = core::result::Result<core::pin::Pin<alloc::boxed::Box<dyn datafusion::physical_plan::RecordBatchStream+Item = core::result::Result<arrow::record_batch::RecordBatch,arrow::error::ArrowError>+core::marker::Send+core::marker::Sync>>,datafusion_common::error::DataFusionError>+core::marker::Send>>
2022-02-22T17:09:19.118515881Z              at ./rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/ptr/mod.rs:188:1
2022-02-22T17:09:19.118623582Z   18: core::ptr::drop_in_place<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future+Output = core::result::Result<core::pin::Pin<alloc::boxed::Box<dyn datafusion::physical_plan::RecordBatchStream+Item = core::result::Result<arrow::record_batch::RecordBatch,arrow::error::ArrowError>+core::marker::Send+core::marker::Sync>>,datafusion_common::error::DataFusionError>+core::marker::Send>>>
2022-02-22T17:09:19.118640092Z              at ./rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/ptr/mod.rs:188:1
2022-02-22T17:09:19.118661405Z   19: core::ptr::drop_in_place<query::exec::context::IOxExecutionContext::execute_stream_partitioned::{{closure}}::{{closure}}>
2022-02-22T17:09:19.118682518Z              at ./rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/ptr/mod.rs:364:26
2022-02-22T17:09:19.118709556Z   20: core::ptr::drop_in_place<core::future::from_generator::GenFuture<query::exec::context::IOxExecutionContext::execute_stream_partitioned::{{closure}}::{{closure}}>>
2022-02-22T17:09:19.118721053Z              at ./rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/ptr/mod.rs:188:1
2022-02-22T17:09:19.118782555Z   21: core::ptr::drop_in_place<query::exec::task::DedicatedExecutor::spawn<core::future::from_generator::GenFuture<query::exec::context::IOxExecutionContext::execute_stream_partitioned::{{closure}}::{{closure}}>>::{{closure}}>
2022-02-22T17:09:19.118797915Z              at ./rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/ptr/mod.rs:177:31
2022-02-22T17:09:19.118852080Z   22: core::ptr::drop_in_place<core::future::from_generator::GenFuture<query::exec::task::DedicatedExecutor::spawn<core::future::from_generator::GenFuture<query::exec::context::IOxExecutionContext::execute_stream_partitioned::{{closure}}::{{closure}}>>::{{closure}}>>
2022-02-22T17:09:19.118860372Z              at ./rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/ptr/mod.rs:188:1
2022-02-22T17:09:19.118913549Z   23: core::ptr::drop_in_place<alloc::boxed::Box<dyn core::future::future::Future+Output = ()+core::marker::Send>>
2022-02-22T17:09:19.118919373Z              at ./rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/ptr/mod.rs:188:1
2022-02-22T17:09:19.118961525Z   24: core::ptr::drop_in_place<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future+Output = ()+core::marker::Send>>>
2022-02-22T17:09:19.118977753Z              at ./rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/ptr/mod.rs:188:1
2022-02-22T17:09:19.119031111Z   25: core::ptr::drop_in_place<(tokio_util::sync::cancellation_token::WaitForCancellationFuture,core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future+Output = ()+core::marker::Send>>)>
2022-02-22T17:09:19.119037545Z              at ./rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/ptr/mod.rs:188:1
2022-02-22T17:09:19.119059951Z   26: query::exec::task::Task::run::{{closure}}
2022-02-22T17:09:19.119077442Z              at ./influxdb_iox/query/src/exec/task.rs:30:9
```

**Comment by alamb** [comment] 2022-02-28 13:43
This looks like a datafusion accounting bug to me. I'll put it on my list to try and find a self-contained reproducer

**Comment by alamb** [comment] 2022-04-04 18:38
This may be fixed by https://github.com/apache/arrow-datafusion/pull/2135

**Closed** 2022-04-06 16:22 UTC
