### ISSUE TITLE
Reload parquet files back into read buffer

### ISSUE THREAD

**Issue by NGA-TRAN** [influxdata/influxdb_iox#1490] opened 2021-05-13 14:41 UTC
__Use case:__
Since memory is limited, cold (or not too hot) data will be removed from read buffer. In situations when the cold data become hot again, we want to reload them back into read buffer. 

__Proposal:__
Bring data from `ObjectStoreOnly` to `ReadBufferAndObjectStore`
TBD: state of this in the life cycle

**Comment by NGA-TRAN** [comment] 2021-05-17 16:22
a/conductor/blob/main/docs/iox-in-tools.md#interacting-with-the-iox-cluster-in-toolus1

**Comment by tustvold** [comment] 2021-11-26 17:43
Closing as duplicate of #3224

**Closed by tustvold** 2021-11-26 17:43 UTC
Labels: performance, read buffer, parquet
