### ISSUE TITLE
PartitionCheckpoint Without Parquet File

### ISSUE THREAD

**Issue by tustvold** [influxdata/influxdb_iox#2209] opened 2021-08-06 10:11 UTC
Currently it is only possible to generate a PartitionCheckpoint associated with a parquet file. With the ability to drop unpersisted data, however, there comes a need to be able to generate a PartitionCheckpoint without any associated data. I suspect it would be valid to only include this in the catalog transactions, and not persist a file, provided the catalog-rebuild from parquet files is aware that a later DatabaseCheckpoint may be inconsistent with an earlier PartitionCheckpoint.

This is likely a requirement to properly fix #2208 and #2207

**Comment by jacobmarble** [comment] 2021-11-13 00:07
@tustvold can this be closed? Looks like #2207 and #2208 are resolved.

**Comment by NGA-TRAN** [comment] 2021-12-10 20:35
@tustvold : this sounds important to avoid bugs. Is this still valid and need our attention soon?

**Comment by tustvold** [comment] 2021-12-10 20:47
@NGA-TRAN I think #3145 and #3146 which motivate this issue end up being just optimisations, as opposed to necessary for correctness. I started implementing this, but in so doing convinced myself that you couldn't get invalid behaviour just sub-optimal. I could be wrong though?

**Comment by NGA-TRAN** [comment] 2021-12-10 21:12
@tustvold I do not know this area well so I let you decide. If you think this is not important and won't help much, close it is a good option 😄

**Comment by crepererum** [comment] 2021-12-13 09:53
Could we be a bit more precise on the "suboptimal but not invalid" behavior here? IIRC the issue is when you delete the entire partition, we don't store any checkpoint for it. I think we still have some subtle bug here that we lead forever-open persistence windows if you have a partition that gets write which is immediately deleted w/o any persistence action in the meantime. The in-mem persistence windows don't track the delete, so databases checkpoints created during the persistence of other partitions will just have a minimum of the never-persisted write. In that case we won't be able to perform replay properly after a day or so.

**Comment by tustvold** [comment] 2021-12-13 10:17
Aah yes, I remember. You need this to correctly handle a sequencer with deletes but not writes. As nothing will checkpoint its position in the stream, stuff will get rotated out of Kafka and eventually the database will error in replay complaining about skipped sequence numbers

> a partition that gets write which is immediately deleted w/o any persistence action in the meantime

I think this is a separate bug if this is the case, it shouldn't be possible to delete unpersisted data. (TBH I question the value of unsequenced delete APIs at all).

**Comment by crepererum** [comment] 2021-12-13 10:48
I wasn't talking about unsequenced data here. I think we're not updating the persistence windows when we receive deletes via a write buffer.

**Comment by tustvold** [comment] 2021-12-13 10:51
Yup #3145, IOx will currently not handle sequencers with only deletes very well - this should probably be fixed

**Closed** 2022-08-26 05:57 UTC
Labels: enhancement, parquet, kafka
