### ISSUE TITLE
Support streaming ingester state to queriers

### ISSUE THREAD

**Issue by domodwyer** [influxdata/influxdb_iox#4567] opened 2022-05-11 14:03 UTC
Currently when an ingester attempts to execute a query on in-memory state for a querier, it buffers all the results in memory before returning all record batches to the querier.

This causes each query to use a (potentially) large amount of RAM to buffer all the records. A query with no predicate pushed down will copy all the table data in memory before returning it to the querier.

This ticket is to implement streaming record batches back to the querier instead of buffering them in memory.

**Comment by alamb** [comment] 2022-05-11 15:06
I think we do a similar thing for actual query results -- more streaming more better as my mother always says 👍

**Comment by alamb** [comment] 2022-06-09 17:27
Assigning this to myself as I believe @domodwyer  is tracking down another issue at the moment

**Comment by alamb** [comment] 2022-06-09 20:14
So there are at least two copies of the data that are buffered (in addition to the `RecordBatch`es the ingester has already):

```text
                  Buffering location             Buffering location #2:
                  #1: turned into a               turned into a single
┌─────────────┐   single RecordBatch              RecordBatch prior to
│┌───────────┐│   to feed into query               sending to querier
││RecordBatch││         engine
│└───────────┘├─────┐
│             │     │
│SnapshotBatch│     │      ┌────────────────────────┐       ┌ ─ ─ ─ ─ ─ ┐        ┌────────────────────────┐
└─────────────┘     │      │                        │                            │                        │
                    ├─────▶│      Query Engine      │──────▶│    ...    │────┬──▶│ IngesterQueryResponse  │
      ...           │      │                        │                        │   │                        │
                    │      └────────────────────────┘       └ ─ ─ ─ ─ ─ ┘    │   └────────────────────────┘
┌─────────────┐     │                                                        │
│┌───────────┐│     │     Runs query engine, which                           │
││RecordBatch││     │     deduplicates and applies                           │
│└───────────┘│─────┘    filters, produces a Stream                          │
│             │                                                            ──┤
│SnapshotBatch│                                                              │
└─────────────┘                                                              │
                                                                     ...     │
                                                                             │
                                                                             │
                                                            data from other  │
                                                               partitions    │
                                                                          ───┘

```

# Plan
I plan remove the extra buffering in at least two stages:
1. Remove buffering #1: by implementing `QueryChunk` for SnapshotBatch rather than `QueryBatch` and let the query engine do the schema adapting
2. Remove buffering #2: find some alternate way to pass partition information along to the querier that doesn't require knowing all the output record batches up front

# Alternates considered
Since the ingester already has all data in RecordBatches, one idea I was toying with was to stop running the query engine at all on the ingester, and instead just do projection / select columns on the ingester and send the result back to the querier.

It seems clear that in the long term, pushing some sort of filtering to the ingester is likely to be helpful, but I was thinking we could bypass a bunch of complexity and buffering by skipping that for now. However, @NGA-TRAN  reminded me that it is important for correctness that the ingester apply deletes (which happens by running a plan)

**Comment by alamb** [comment] 2022-06-13 19:23
Update: I tried the approach sketched in https://github.com/influxdata/influxdb_iox/pull/4830 which was to treat all `SnapshotBatch` es as though they were `QueryChunk`s but that has resulted in some schema mismatches which I am still debugging.  I believe the buffering into a single `RecordBatch` was actually to avoid these errors.

I don't fully understand the root cause of the error yet, but I will keep working on it tomorrow.

**Closed** 2022-06-16 16:12 UTC

**Comment by alamb** [comment] 2022-06-16 16:13
Closed in https://github.com/influxdata/influxdb_iox/pull/4875
