### ISSUE TITLE
Remove OG architecture codebase

### ISSUE THREAD

**Issue by alamb** [influxdata/influxdb_iox#4245] opened 2022-04-06 15:54 UTC
The code that runs the "OG" architecture is destined for the bitbucket as it has been overtaken by the NG architecture

Maintaining two parallel codebases slows down the implementation of NG as it makes shared code harder to change (has to work with both paradigms), search (have to know what is used by OG / NG) as well as takes longer to compile, etc

Specifically, removing OG would mean at least
- [ ] Removing `server` crate
- [ ] Removing `db` crate
- [ ] Removing `run`, `router` and `database` commands
- [ ] Removing `ioxd_router` and `ioxd_database` crates
- [ ] Removing unused parts of `data_types`

And probably much more

**Comment by carols10cents** [comment] 2022-05-09 18:38
Closing this as a duplicate of #4450 :)

**Closed by carols10cents** 2022-05-09 18:38 UTC
