### ISSUE TITLE
Speed up compilation by reducing the number of Rust dependencies

### ISSUE THREAD

**Issue by e-dard** [influxdata/influxdb_iox#1231] opened 2021-04-16 08:04 UTC
There is nothing specifically actionable from this ticket until someone goes and pokes around a bit and figures out what we could do to help reduce our dependencies.

### Problem

I'm already starting to see huge number of dependencies being pulled into many different crates when building at the crate or project level. Rust is slow enough to compile as it is, but we can control our dependencies to try and speed things up that way.

### Initial Steps

I'm open to ideas but maybe:

- [ ] determine how many dependencies we have and where they stem from (`cargo tree | wc -l` gives me 1233 lines).
- [ ] look for any dependencies that we are using little of, but are accounting for a lot of the bloat? We could just not use those and instead implement the dependency ourselves (clients libraries and SDKs can be a good example of these, e.g., aws/gcp/azure object store clients).
- [ ] can we reduce any cross-crate dependencies by maybe just replicating types from one crate in another and implementing `From` where appropriate to convert from one to the other?

**Comment by alamb** [comment] 2021-04-16 11:01
I think the `prost` / protobuf handling libraries are an obvious place to target to slim down dependencies as they bring in a lot

We could also make the arrow dependencies more fine grained (like maybe make `arrow_deps` `arrow_flight_deps` and `datafusion_deps`) as arrow has significantly fewer dependencies than datafusion or flight

**Comment by crepererum** [comment] 2021-04-19 15:06
I think the issue is that we have too many different dependencies, rather than multiple versions of them (or at least the latter one isn't a massive issue). For [`7b67ae498bc5f89306cefc9946a9363759dbefa6`](https://github.com/influxdata/influxdb_iox/tree/7b67ae498bc5f89306cefc9946a9363759dbefa6)

```shell
cargo tree --workspace | sed -e 's/^[^a-zA-Z0-9_-]*//' -e 's/\s*([^)]*)\s*//g' -e '/^$/d' | sort -u
```

we get the following version list (which has 372 entries):

<details>

```text
addr2line v0.14.1
adler v1.0.2
ahash v0.4.7
ahash v0.7.2
aho-corasick v0.7.15
alloc-no-stdlib v2.0.1
alloc-stdlib v0.2.1
ansi_term v0.11.0
ansi_term v0.12.1
anyhow v1.0.40
arrayvec v0.5.2
arrow_deps v0.1.0
arrow-flight v4.0.0-SNAPSHOT
arrow v4.0.0-SNAPSHOT
assert_cmd v1.0.3
assert-json-diff v1.1.0
async-stream-impl v0.3.0
async-stream v0.3.0
async-trait v0.1.48
atty v0.2.14
autocfg v1.0.1
azure_core v0.1.0
azure_storage v0.1.0
backtrace v0.3.56
base64 v0.12.3
base64 v0.13.0
bindgen v0.56.0
bitflags v1.2.1
block-buffer v0.9.0
brotli-decompressor v2.3.1
brotli v3.3.0
bstr v0.2.15
build-dependencies]
byteorder v1.4.3
bytes v1.0.1
cast v0.2.5
cc v1.0.67
cexpr v0.4.0
cfg_aliases v0.1.1
cfg-if v0.1.10
cfg-if v1.0.0
chrono v0.4.19
clang-sys v1.2.0
clap v2.33.3
cloud-storage v0.9.0
colored v1.9.3
const_fn v0.4.6
cpuid-bool v0.1.2
crc32fast v1.2.1
criterion-plot v0.4.3
criterion v0.3.4
croaring-sys v0.4.6
croaring v0.4.6
crossbeam-channel v0.5.1
crossbeam-deque v0.8.0
crossbeam-epoch v0.9.3
crossbeam-queue v0.3.1
crossbeam-utils v0.8.3
crossbeam v0.8.0
crypto-mac v0.10.0
csv-core v0.1.10
csv v1.1.6
ct-logs v0.8.0
dashmap v4.0.2
datafusion v4.0.0-SNAPSHOT
data_types v0.1.0
dev-dependencies]
difference v2.0.0
digest v0.9.0
dirs-next v2.0.0
dirs-sys-next v0.1.2
dirs-sys v0.3.5
dirs v1.0.5
dirs v3.0.1
doc-comment v0.3.3
dotenv v0.15.0
dtoa v0.4.8
either v1.6.1
encode_unicode v0.3.6
encoding_rs v0.8.28
env_logger v0.8.3
extend v0.1.2
failure_derive v0.1.8
failure v0.1.8
fixedbitset v0.2.0
flatbuffers v0.8.3
flate2 v1.0.20
float-cmp v0.8.0
fnv v1.0.7
foreign-types-shared v0.1.1
foreign-types v0.3.2
form_urlencoded v1.0.1
fs_extra v1.2.0
futures-channel v0.3.14
futures-core v0.3.14
futures-executor v0.3.14
futures-io v0.3.14
futures-macro v0.3.14
futures-sink v0.3.14
futures-task v0.3.14
futures-test v0.3.14
futures-util v0.3.14
futures v0.3.14
generated_types v0.1.0
generic-array v0.14.4
getrandom v0.1.16
getrandom v0.2.2
gimli v0.23.0
glob v0.3.0
google_types v0.1.0
h2 v0.3.2
half v1.7.1
hashbrown v0.11.2
hashbrown v0.9.1
heck v0.3.2
hex v0.4.3
hmac v0.10.1
httparse v1.3.6
http-body v0.4.1
httpdate v0.3.2
http v0.2.4
human_format v1.0.3
humantime v2.1.0
hyper-rustls v0.22.1
hyper-tls v0.5.0
hyper v0.14.5
idna v0.2.2
indexmap v1.6.2
Inflector v0.11.4
influxdb2_client v0.1.0
influxdb_iox_client v0.1.0
influxdb_iox v0.1.0
influxdb_line_protocol v0.1.0
influxdb_tsm v0.1.0
ingest v0.1.0
instant v0.1.9
integer-encoding v1.1.7
internal_types v0.1.0
ipnet v2.3.0
itertools v0.10.0
itertools v0.9.0
itoa v0.4.7
jobserver v0.1.21
jsonwebtoken v7.2.0
lazycell v1.3.0
lazy_static v1.4.0
lexical-core v0.7.5
libc v0.2.93
libloading v0.7.0
libm v0.1.4
libm v0.2.1
lock_api v0.4.3
logfmt v0.1.0
log v0.4.14
lz4-sys v1.9.2
lz4 v1.23.2
matchers v0.0.1
matches v0.1.8
md5 v0.7.0
memchr v2.3.4
memoffset v0.6.3
mem_qe v0.1.0
mime v0.3.16
miniz_oxide v0.4.4
mio v0.7.11
mockito v0.26.0
multimap v0.8.3
mutable_buffer v0.1.0
native-tls v0.2.7
nom v5.1.2
normalize-line-endings v0.3.0
num-bigint v0.2.6
num-bigint v0.3.2
num-complex v0.3.1
num_cpus v1.13.0
num-integer v0.1.44
num-iter v0.1.42
num-rational v0.3.2
num-traits v0.2.14
num v0.3.1
oauth2 v4.0.0-alpha.3
object_store v0.1.0
object v0.23.0
observability_deps v0.1.0
once_cell v1.7.2
oorandom v11.1.3
opaque-debug v0.3.0
openssl-probe v0.1.2
openssl-sys v0.9.61
openssl v0.10.33
opentelemetry-jaeger v0.11.0
opentelemetry-prometheus v0.5.0
opentelemetry v0.12.0
ordered-float v1.1.1
ordered-float v2.1.1
ouroboros_macro v0.8.3
ouroboros v0.8.3
packed_simd_2 v0.3.4
packers v0.1.0
panic_logging v0.1.0
parking_lot_core v0.8.3
parking_lot v0.11.1
parquet_file v0.1.0
parquet-format v2.6.1
parquet v4.0.0-SNAPSHOT
paste v1.0.5
peeking_take_while v0.1.2
pem v0.8.3
percent-encoding v2.1.0
permutation v0.2.5
petgraph v0.5.1
pin-project-internal v0.4.28
pin-project-internal v1.0.6
pin-project-lite v0.2.6
pin-project v0.4.28
pin-project v1.0.6
pin-utils v0.1.0
pkg-config v0.3.19
plotters-backend v0.3.0
plotters-svg v0.3.0
plotters v0.3.0
ppv-lite86 v0.2.10
predicates-core v1.0.2
predicates-tree v1.0.2
predicates v1.0.7
prettytable-rs v0.8.0
proc-macro2 v1.0.24
proc-macro-error-attr v1.0.4
proc-macro-error v1.0.4
proc-macro-hack v0.5.19
proc-macro-nested v0.1.7
prometheus v0.11.0
prost-build v0.7.0
prost-derive v0.7.0
prost-types v0.7.0
prost v0.7.0
protobuf v2.22.1
query v0.1.0
quick-error v1.2.3
quote v1.0.9
rand_chacha v0.2.2
rand_chacha v0.3.0
rand_core v0.5.1
rand_core v0.6.2
rand_distr v0.4.0
rand v0.7.3
rand v0.8.3
rayon-core v1.9.0
rayon v1.5.0
read_buffer v0.1.0
regex-automata v0.1.9
regex-syntax v0.6.23
regex v1.4.5
remove_dir_all v0.5.3
reqwest v0.11.3
ring v0.16.20
routerify v2.0.0-beta-2
rusoto_core v0.46.0
rusoto_credential v0.46.0
rusoto_s3 v0.46.0
rusoto_signature v0.46.0
rustc-demangle v0.1.18
rustc-hash v1.1.0
rustc_version v0.2.3
rustls-native-certs v0.5.0
rustls v0.19.0
RustyXML v0.3.0
ryu v1.0.5
same-file v1.0.6
scopeguard v1.1.0
sct v0.6.1
semver-parser v0.7.0
semver v0.9.0
serde_cbor v0.11.1
serde_derive v1.0.125
serde_json v1.0.64
serde_regex v1.1.0
serde_urlencoded v0.6.1
serde_urlencoded v0.7.0
serde v1.0.125
serde-xml-rs v0.4.1
server v0.1.0
sha2 v0.9.3
sharded-slab v0.1.1
shlex v0.1.1
signal-hook-registry v1.3.0
simple_asn1 v0.4.1
slab v0.4.2
smallvec v1.6.1
snafu-derive v0.6.10
snafu v0.6.10
snap v1.0.4
socket2 v0.4.0
spin v0.5.2
sqlparser v0.8.0
sqlparser v0.9.0
stable_deref_trait v1.2.0
standback v0.2.17
static_assertions v1.1.0
string-interner v0.12.2
strsim v0.8.0
structopt-derive v0.4.14
structopt v0.3.21
subtle v2.4.0
synstructure v0.12.4
syn v1.0.67
tempfile v3.2.0
termcolor v1.1.2
term v0.5.2
test_helpers v0.1.0
textwrap v0.11.0
thiserror-impl v1.0.24
thiserror v1.0.24
thread_local v1.1.3
threadpool v1.8.1
thrift v0.13.0
tikv-jemallocator v0.4.1
tikv-jemalloc-sys v0.4.1+5.2.1-patched
time-macros-impl v0.1.1
time-macros v0.1.1
time v0.1.43
time v0.2.26
tinytemplate v1.2.1
tinyvec_macros v0.1.0
tinyvec v1.2.0
tokio-macros v1.1.0
tokio-native-tls v0.3.0
tokio-rustls v0.22.0
tokio-stream v0.1.5
tokio-util v0.6.6
tokio v1.5.0
tonic-build v0.4.1
tonic-health v0.3.0
tonic v0.4.1
tower-layer v0.3.1
tower-service v0.3.1
tower v0.4.6
tracing-attributes v0.1.15
tracing-core v0.1.17
tracing-futures v0.2.5
tracing-log v0.1.2
tracing-opentelemetry v0.11.0
tracing-serde v0.1.2
tracing-subscriber v0.2.17
tracing v0.1.25
tracker v0.1.0
treeline v0.1.0
try-lock v0.2.3
typenum v1.13.0
unicode-bidi v0.3.5
unicode-normalization v0.1.17
unicode-segmentation v1.7.1
unicode-width v0.1.8
unicode-xid v0.2.1
untrusted v0.7.1
url v2.2.1
uuid v0.8.2
vec_map v0.8.2
version_check v0.9.3
wait-timeout v0.2.0
walkdir v2.3.2
wal v0.1.0
want v0.3.0
webpki-roots v0.21.1
webpki v0.21.4
which v3.1.1
which v4.1.0
xml-rs v0.8.3
zeroize v1.2.0
zstd-safe v3.1.0+zstd.1.4.9
zstd-sys v1.5.0+zstd.1.4.9
zstd v0.7.0+zstd.1.4.9
```

<details/>

Note that `cargo tree` without any de-duplication overestimates the dependency graph size since crate versions can be shared.

**Comment by shepmaster** [comment] 2021-11-12 16:46
Looking at multiple crate versions (`cargo tree -d`), it's not as bad as I expected. Only 7 crates have multiple versions, and no more than two:

|crate|versions|build time|
|-|-|-|
|ansi_term|v0.11.0, v0.12.1|0.3s|
|comfy-table|v4.1.1, v5.0.0|1.0s|
|nom|v6.1.2, v7.0.0|1.5s|
|ordered-float|v1.1.1, v2.8.0|0.3s|
|strum|v0.21.0, v0.22.0|0.1s|
|strum_macros|v0.21.1, v0.22.0|1.75s|
|which|v3.1.1, v4.2.2|0.2s|

**Comment by shepmaster** [comment] 2021-11-12 16:59
Using [Cargo's build timing](https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#timings) for a clean build, the ten longest steps are:

|name|time|codegen time|features|
|--|--|--|--|
|influxdb_iox v0.1.0 bin "influxdb_iox"|40.0s|0.0s (0%)|default, jemalloc_replacing_malloc, tikv-jemalloc-sys|
|zstd-sys v1.6.1+zstd.1.5.0 build script (run)|31.7s|0.0s (0%)|legacy, std|
|rdkafka-sys v4.1.0+1.7.0 build script (run)|21.8s|0.0s (0%)|libz, libz-sys|
|tikv-jemalloc-sys v0.4.2+5.2.1-patched.2 build script (run)|17.6s|0.0s (0%)|background_threads_runtime_support, default, unprefixed_malloc_on_supported_platforms|
|lz4-sys v1.9.2 build script (run)|13.1s|0.0s (0%)|
|arrow v6.1.0|11.9s|4.9s (41%)|comfy-table, csv, csv_crate, default, flatbuffers, ipc, prettyprint, rand, test_utils|
|datafusion v5.1.0|10.9s|5.6s (52%)|
|server v0.1.0|8.3s|4.0s (48%)|default|
|hyper v0.14.14|6.4s|0.0s (0%)|client, default, full, h2, http1, http2, runtime, server, socket2, stream, tcp|
|croaring-sys v0.5.1 build script (run)|6.2s|0.0s (0%)|

My takeaway here is that the **C** dependencies are large contributors to overall clean build time. These account for 40% of the total CPU time spent during the build (not wall clock time / accounting for parallelism)

**Comment by alamb** [comment] 2022-07-18 14:34
The problem is that each individual PR is like "it is only one more dependency, no big deal" 

But it takes actual effort to remove the dependencies...

**Comment by crepererum** [comment] 2022-07-18 16:22
@alamb I think the slow growth between the larger jumps is also due to dependency updates. Often some but not all direct weekly dependencies require updated indirect dependencies so you end up with some crates being compiled twice in different versions. I usually just approve these kind of dependabot PRs because after a while, the outdated indirect dependencies are not required anymore because all direct dependencies have updated their code (resulting in PRs that make the graph jump back). Plus the maintenance burden of orchestrating updates of indirect dependencies is just not worth it.

I've also looked at the deps quite a bit in the last week. I think "one more dep" is not really something that our developers do often, but its more that our direct deps use yet-another-blah-crate for simple tasks, so it feels we have too many compilation helpers or tiny-feature crates in our collection, many with duplicate functionality. But this is more of a community issue I think.

**Comment by alamb** [comment] 2022-07-18 16:52
> I think "one more dep" is not really something that our developers do often

Indeed -- I think most developers only do "one more dep" rarely, however, a project as a whole ends up getting the transitive union of all such "one more dep" uses ;) So no individual developer or project is bad, but intead we are devoured by slow growth of dependency creep

**Comment by aierui** [comment] 2022-08-25 15:34
❤️

**Comment by crepererum** [comment] 2022-08-25 15:42
Update:

![package_growth](https://user-images.githubusercontent.com/1529400/186709915-f4828293-d0c6-4b1e-b4a7-246bf1fb5f26.svg)

Looks like @tustvold 's work on `object_store_rs` really pays off.

**Comment by crepererum** [comment] 2022-10-21 10:03
Update:

![package_growth](https://user-images.githubusercontent.com/1529400/197170000-04a653a1-0680-443e-9ab5-10ac900f36da.svg)

We are somewhat steady at 500 + a bit. However many of these packages are support packages that are basically never compiled (e.g. because they are for windows or WASM). We have some duplicates and we constantly try to reduce them (e.g. using upstream PRs), but I think this cannot be avoided.

**Comment by carols10cents** [comment] 2022-10-21 16:06
I say we close this, then, and open a new issue if we notice the number of dependencies getting out of hand in the future.

**Closed by carols10cents** 2022-10-21 16:06 UTC
Labels: build, developer experience
