### ISSUE TITLE
Memory grows without bound when ingesting from kafka leading to OOM

### ISSUE THREAD

**Issue by alamb** [influxdata/influxdb_iox#2353] opened 2021-08-19 13:29 UTC
__Steps to reproduce:__
Ingest data via Kafka

__Expected behaviour:__
Memory usage should stay within the configured limits

__Actual behaviour:__
Memory grows until IOx is killed due to exceeding its memory limits

![Screen Shot 2021-08-19 at 9 28 15 AM](https://user-images.githubusercontent.com/490673/130076904-796d9104-ef90-4cb0-99c4-005581201956.png)

You can see the blue line on the bottom increasing and the dropping down when it is OOM killed

This screen shot shows the orange line (what IOx thinks is used by chunks) leveling off even though the blue line (memory allocated) goes up (the flat line to the right is due to another unrelated problem)
![image (2)](https://user-images.githubusercontent.com/490673/130077058-bb784adb-508e-4678-afaf-02817b9f9676.png)

__Environment info:__

InfluxData internal system

**Comment by alamb** [comment] 2021-08-19 13:30
I believe @crepererum  is working on this so assigning to him

**Comment by alamb** [comment] 2021-08-19 13:31
When we tried ingesting directly from line protocol without kafka involved the memory leak no longer occured: 

![Screen Shot 2021-08-19 at 9 30 59 AM](https://user-images.githubusercontent.com/490673/130077289-344e4e71-93d9-4409-8a73-de949efe1d99.png)

**Comment by mkmik** [comment] 2021-08-23 22:49
It appears this is a red herring; the instance we tested the kafka write path with was receiving a pattern of writes that exacerbated the issue already reported in #2252. We reproduced the same behavior even without the kafka write buffer enabled.

Closed as dupe of #2252

**Closed by mkmik** 2021-08-23 22:49 UTC
