### ISSUE TITLE
Document requirement on `protoc`

### ISSUE THREAD

**Issue by shepmaster** [influxdata/influxdb_iox#465] opened 2020-11-20 14:07 UTC
On a machine without `protoc` installed, `cargo build` reports:

```
Failed to find the protoc binary. The PROTOC environment variable is not set, there is no bundled protoc for this platform, and protoc is not in the PATH'
```

**Comment by domodwyer** [comment] 2020-11-27 14:47
Hey @shepmaster 

I had a go at reproducing this to make sure I was doc'ing the right reasoning, but I couldn't actually reproduce it:

```bash
vps608690:influxdb_iox % git clone git@github.com:influxdata/influxdb_iox.git
    <snip>

vps608690:influxdb_iox % which protoc
protoc not found

vps608690:influxdb_iox % cargo build --workspace
    Finished dev [unoptimized + debuginfo] target(s) in 0.87s
```

I tried on macOS and Linux, neither have `protoc` in PATH and the linux box doesn't have it installed at all. Is there some step I've missed to trigger this? From what I can see [tonic is using prost] which doesn't _explicitly_ say `protoc` is a [requirement](https://github.com/danburkert/prost), but that doesn't that's the case!

I did however discover we have a dependency on clang to facilitate the `croaring` build so I'll doc that until we remove it in #234.

<details><summary>clang error</summary>
<p>

```text
The following warnings were emitted during compilation:

warning: couldn't execute `llvm-config --prefix` (error: No such file or directory (os error 2))
warning: set the LLVM_CONFIG_PATH environment variable to the full path to a valid `llvm-config` executable (including the executable itself)

error: failed to run custom build command for `croaring-sys v0.4.5`

Caused by:
  process didn't exit successfully: `/home/dom/influxdb_iox/target/debug/build/croaring-sys-ecfc644dba7d9737/build-script-build` (exit code: 101)
  --- stdout
  TARGET = Some("x86_64-unknown-linux-gnu")
  OPT_LEVEL = Some("0")
  HOST = Some("x86_64-unknown-linux-gnu")
  CC_x86_64-unknown-linux-gnu = None
  CC_x86_64_unknown_linux_gnu = None
  HOST_CC = None
  CC = None
  CFLAGS_x86_64-unknown-linux-gnu = None
  CFLAGS_x86_64_unknown_linux_gnu = None
  HOST_CFLAGS = None
  CFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("true")
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
  CC_x86_64-unknown-linux-gnu = None
  CC_x86_64_unknown_linux_gnu = None
  HOST_CC = None
  CC = None
  CFLAGS_x86_64-unknown-linux-gnu = None
  CFLAGS_x86_64_unknown_linux_gnu = None
  HOST_CFLAGS = None
  CFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
  running: "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-m64" "-Wall" "-Wextra" "-march=native" "-o" "/home/dom/influxdb_iox/target/debug/build/croaring-sys-53a9c55d5127ad51/out/CRoaring/roaring.o" "-c" "CRoaring/roaring.c"
  exit code: 0
  AR_x86_64-unknown-linux-gnu = None
  AR_x86_64_unknown_linux_gnu = None
  HOST_AR = None
  AR = None
  running: "ar" "cq" "/home/dom/influxdb_iox/target/debug/build/croaring-sys-53a9c55d5127ad51/out/libroaring.a" "/home/dom/influxdb_iox/target/debug/build/croaring-sys-53a9c55d5127ad51/out/CRoaring/roaring.o"
  exit code: 0
  running: "ar" "s" "/home/dom/influxdb_iox/target/debug/build/croaring-sys-53a9c55d5127ad51/out/libroaring.a"
  exit code: 0
  cargo:rustc-link-lib=static=roaring
  cargo:rustc-link-search=native=/home/dom/influxdb_iox/target/debug/build/croaring-sys-53a9c55d5127ad51/out
  cargo:warning=couldn't execute `llvm-config --prefix` (error: No such file or directory (os error 2))
  cargo:warning=set the LLVM_CONFIG_PATH environment variable to the full path to a valid `llvm-config` executable (including the executable itself)

  --- stderr
  thread 'main' panicked at 'Unable to find libclang: "couldn\'t find any valid shared libraries matching: [\'libclang.so\', \'libclang-*.so\', \'libclang.so.*\', \'libclang-*.so.*\'], set the `LIBCLANG_PATH` environment variable to a path where one of these files can be found (invalid: [])"', /home/dom/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.53.3/src/lib.rs:1956:31
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: build failed
```
</p>
</details>

[tonic is using prost]: https://github.com/hyperium/tonic/tree/master/tonic-build

**Comment by domodwyer** [comment] 2020-12-03 17:46
I'm going to close this for the time being - if it bites again feel free to reopen and I'll take another look at it!

**Closed by domodwyer** 2020-12-03 17:46 UTC
Labels: good first issue

**Comment by alamb** [comment] 2020-12-03 19:22
was surprised by this but I agree that `protoc` doesn't seem to be needed (I couldn't help myself but double check):

Here was what I needed to do

fire up teh dockerz using standard rust docker image:
```
cd /tmp
git clone git@github.com:influxdata/influxdb_iox.git
docker run  -v /tmp/influxdb_iox:/influxdb_iox -it rust bin/bash
```

Then in the docker container:

```
# install dependencies
apt-get update
apt-get install cmake -y
apt-get install libclang-dev
apt-get install llvm -y
apt-get install clang -y

# Install flatbuffers
git clone -b v1.12.0https://github.com/google/flatbuffers.git
cd flatbuffers
cmake -G "Unix Makefiles"  -DCMAKE_BUILD_TYPE=Release
make  -j $(nproc) install

# build IOx without issue:
cd /influxdb_iox/
cargo build
```

It appears to me that prost now bundles pre-built protoc binaries:

```
root@8d8dbeb6dedf:/influxdb_iox# ls -ltr /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/prost-build-0.6.1/third-party/protobuf
total 28476
-rw-r--r-- 1 root root     1732 Jun 13  2019 LICENSE
-rwxr-xr-x 1 root root  2639360 Jan 12  2020 protoc-win32.exe
-rwxr-xr-x 1 root root 11773784 Jan 12  2020 protoc-osx-x86_64
-rwxr-xr-x 1 root root  5068728 Jan 12  2020 protoc-linux-x86_64
-rwxr-xr-x 1 root root  4684700 Jan 12  2020 protoc-linux-x86_32
-rwxr-xr-x 1 root root  4974596 Jan 12  2020 protoc-linux-aarch_64
drwxr-xr-x 3 root root     4096 Dec  3 18:39 include
root@8d8dbeb6dedf:/influxdb_iox# 
```

**Comment by shepmaster** [comment] 2020-12-04 03:05
> It appears to me that `prost-build` now bundles pre-built protoc binaries:

Perhaps that's the problem. I'm doing this build on an Apple Silicon device.

```
% git show -s
commit 4ec75a4f227e7a634af7d41f850a11e2ac4f1708 (HEAD -> main, origin/main, origin/HEAD)
Author: Andrew Lamb <alamb@influxdata.com>
Date:   Thu Dec 3 12:31:02 2020 -0500

% cargo build
   Compiling prost-build v0.6.1
   Compiling arrow v3.0.0-SNAPSHOT (https://github.com/apache/arrow.git?rev=db20c7a611adac7be5cdd9350792852345f5b6b4#db20c7a6)
   Compiling croaring-sys v0.4.5
error: failed to run custom build command for `prost-build v0.6.1`

Caused by:
  process didn't exit successfully: `/Users/shepmaster/Projects/influxdb_iox/target/debug/build/prost-build-dcca0901011e0675/build-script-build` (exit code: 101)
  --- stderr
  thread 'main' panicked at 'Failed to find the protoc binary. The PROTOC environment variable is not set, there is no bundled protoc for this platform, and protoc is not in the PATH', /Users/shepmaster/.cargo/registry/src/github.com-1ecc6299db9ec823/prost-build-0.6.1/build.rs:97:10
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

> The PROTOC environment variable is not set, there is no bundled protoc **for this platform**, and protoc is not in the PATH

**Comment by domodwyer** [comment] 2020-12-04 10:47
Thanks @shepmaster that clears it up!

I've made #524 to track Apple Silicon build support w.r.t this - it looks like it'll be resolved in the next day or two 👍
